apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: k8s-spring-boot
  name: k8s-spring-boot
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: k8s-spring-boot
    spec:
      containers:
        - image: sashivijaya/k8s-spring-boot
          name: k8s-spring-boot
          ports:
            - name: k8s-spring-boot
              containerPort: 8080
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: k8s-spring-boot
  name: k8s-spring-boot
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: k8s-spring-boot
---
kind: Service
apiVersion: v1
metadata:
  name: k8s-spring-boot
spec:
  selector:
    app: k8s-spring-boot
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-spring-boot
spec:
  selector:
    matchLabels:
      app: k8s-spring-boot
      tier: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: k8s-spring-boot
        tier: backend
    spec:
      containers:
        - name: k8s-spring-boot
          image: sashivijaya/k8s-spring-boot:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080