apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: k8s-spring-boot
  name: spring-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: k8s-spring-boot
    spec:
      containers:
        - image: sashivijaya/k8s-spring-boot
          name: k8s-spring-boot
          ports:
            - name: k8s-spring-boot
              containerPort: 8080
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: k8s-spring-boot
  name: k8s-spring-boot
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: springboot
